#! /bin/sh

ID=1
APP="Brightness"

function data {
    local BRIGHTNESS=$(xbacklight -get)
    local value=${BRIGHTNESS}%

    echo ${value}
}

function icon {
    local DATA=$(data)
    local icons="$HOME/.config/dunst/scripts/brightness/assets/icons/"
    local icon="${icons}1.svg"

    echo ${icon}
}

function notification {
    local ICON=$(icon)
    local DATA=$(data)

    dunstify -i ${ICON} -r ${ID} -a ${APP} ${DATA}
}

notification
