#! /bin/sh

BGreen="\e[1;32m"
BYellow="\e[1;33m"
reset="\e[0m"

path="$(dirname $(readlink -e ${0}))"
slice="/assets/building"

root="${path%%${slice}}"


function backup() {
  if [[ -f "$HOME/.zshrc" ]]
  then
    mv "$HOME/.zshrc" "$HOME/.zshrc.backup"
  fi

  if [[ -d "$HOME/.config" ]]
  then
    mv "$HOME/.config/" "$HOME/.config.backup"
  fi
}

function configuration() {
    local home="${root}/dotfiles"

    cp -r "${home}/.config/" "$HOME/.config/"
    cp "${home}/.zshrc" "$HOME/.zshrc"
}

function main() {
    backup
    echo -e "[${BGreen}*${reset}] Modified files have been backed up."
    configuration
    echo -e "[${BGreen}*${reset}] Dotfiles copied to home directory"
}

main