#! /bin/sh

BGreen="\e[1;32m"
BYellow="\e[1;33m"
reset="\e[0m"

path="$(dirname $(readlink -e ${0}))"
slice="/assets/building"

root="${path%%${slice}}"
# echo "${root}"


function backup() {
  if [[ -f "$HOME/.zshrc" ]]
  then
    mv "$HOME/.zshrc" "$HOME/.zshrc.backup"
  fi

  if [[ -f "$HOME/.bashrc" ]]
  then
    mv "$HOME/.bashrc" "$HOME/.bashrc.backup"
  fi

  if [[ -d "$HOME/.config" ]]
  then
    mv "$HOME/.config/" "$HOME/.config.backup"
  fi
}

function configuration() {
    local home="${root}/dotfiles"

    cp -r "${home}/.config/ $HOME/.config/"
    cp -r "${home}/.*rc $HOME/."
}

function main() {
    echo -e "[${BYellow}*${reset}] A backup copy of the modified files is created .."
    backup
    echo -e "[${BGreen}*${reset}] Modified files have been backed up.\n"
    echo -e "[${BYellow}*${reset}] Copying dotfiles to home directory .."
    configuration
    echo -e "[${BGreen}*${reset}] Dotfiles copied to home directory"
}

# main
