#! /bin/sh

## Editor
# Launching the editor
alias edit='nvim'
# Run the editor as superuser
alias sedit='sudo nvim'

## ls
# Auto color correction (inherited)
alias ls='ls --color=auto'
# Output or all files (including hidden ones)
alias la='ls -a'
# Output only hidden files
alias la.='ls -d .*'
# List output
alias ll='ls -l'
# List all files (including hidden ones)
alias lla='ls -la'

## clear
alias cl='clear'
alias cls='clear'

## mkdir
# Creation of parents in case of absence and information about the catalog
alias mkdir='mkdir -pv'

## Config editing
# bspwm
alias ecb='sedit ~/.config/bspwm/bspwmrc'
# sxhkd
alias ecx='sedit ~/.config/sxhkd/sxhkdrc'

## ping
# Checking the connection with 3 requests
alias ping='ping -c 3 archlinux.org'
