#! /bin/sh

ID=2
APP="Volume"

function data {
    local MUTE=$(pulsemixer --get-mute)
    local VOLUME=$(pulsemixer --get-volume)

    if [[ ${MUTE} != 1 ]] ; then
        if [[ ${#VOLUME} = 7 ]] ; then
            local value=${VOLUME::-3}%
        else
            local value=${VOLUME::-2}%
        fi
    else
        local value='Mute'
    fi

  echo ${value}
}

function icon {
    local DATA=$(data)
    local icons="$HOME/.config/dunst/scripts/volume/assets/icons/"
    if [[ "${DATA}" == "Mute" ]] ; then
      local icon="${icons}mute.svg"
    else
      local icon="${icons}1.svg"
    fi

    echo ${icon}
}

function notification {
    local ICON=$(icon)
    local DATA=$(data)

    dunstify -i ${ICON} -r ${ID} -a ${APP} ${DATA}
}

notification
