#!/bin/sh

source "$HOME/.config/i3lock/scripts/wallpaper/wallpaperrc"
background=${wallpaper}
foreground="ffffff"
alfa="00000000"
font="JetBrains Mono"

i3lock \
--inside-color="${alfa}" \
--ring-color="${alfa}" \
--insidever-color="${alfa}" \
--ringver-color="${alfa}" \
--insidewrong-color="${alfa}" \
--ringwrong-color="${alfa}" \
--line-color="${alfa}" \
--keyhl-color="${alfa}" \
--bshl-color="${alfa}" \
--separator-color="${alfa}" \
\
--image=$background \
\
--time-str="%H:%M" \
--time-color="$foreground" \
--time-font="$font" \
--date-str="%A, %m %Y" \
--date-color="$foreground" \
--date-font="$font" \
\
--keylayout 1 \
--layout-color="${foreground}" \
\
--noinput-text="Enter password .." \
\
--verif-text="Verification .." \
--verif-color="${foreground}" \
--verif-font="${font}" \
\
--wrong-text="Incorrect, try again .." \
--wrong-color="${foreground}" \
--wrong-font="$font" \
