#! /bin/sh


foreground="ffffff"
alfa="00000000"

font="JetBrains Mono"

i3lock \
--no-unlock-indicator \
\
--ignore-empty-password \
\
--image=".config/i3lock/assets/image/background.png" \
--fill \
\
--time-str="%H:%M" \
--time-color="${foreground}" \
--time-font="${font}" \
--time-size="34" \
\
--date-str="%A, %m %Y" \
--date-color="${foreground}" \
--date-font="${font}" \
--date-size="22" \
\
--keylayout 1 \
--layout-color="${foreground}" \
--layout-font="${font}" \
--layout-size="18" \