#! /bin/sh

function get {
    if [ -f "$HOME/Images/wallpapers/desktop.png" ]
    then
        local wallpaper="$HOME/Images/wallpapers/desktop.png"
    else
        local wallpaper="$HOME/.config/bspwm/scripts/wallpaper/assets/image/desktop.png"
    fi
    echo "${wallpaper}"
}

wallpaper=$(get)
feh --no-fehbg --bg-fill "${wallpaper}"
